// automatically generated by the FlatBuffers compiler, do not modify

export enum orbitType{
  /**
   *0
   */
  ORBIT = 0,

  /**
   *1
   */
  DOCKED = 1,

  /**
   *2
   */
  LANDING = 2,

  /**
   *3
   */
  IMPACT = 3
}

